sudo: false
language: d

os:
 - linux
 - osx

d:
 - ldc
 - ldc-beta
 - dmd
 - dmd-beta

env:
 - ARCH="x86_64"

matrix:
  include:
    - {os: linux, d: ldc-beta, env: ARCH="x86", addons: {apt: {packages: [[gcc-multilib]]}}}
    - {os: linux, d: ldc, env: ARCH="x86", addons: {apt: {packages: [[gcc-multilib]]}}}
    - {os: linux, d: dmd-beta, env: ARCH="x86", addons: {apt: {packages: [[gcc-multilib]]}}}
    - {os: linux, d: dmd, env: ARCH="x86", addons: {apt: {packages: [[gcc-multilib]]}}}

install:
    - |
      if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        curl -L "https://github.com/ninja-build/ninja/releases/download/v1.7.2/ninja-linux.zip" -o ninja-linux.zip
        sudo unzip ninja-linux.zip -d /usr/local/bin
        sudo chmod 755 /usr/local/bin/ninja
        sudo add-apt-repository -y ppa:deadsnakes/ppa
        sudo apt-get -y update
        sudo apt-get -y install python3.6
        curl https://bootstrap.pypa.io/get-pip.py | sudo python3.6
        sudo pip3 install meson
      fi

packages:
  - pkg-config

script:
 - echo "$ARCH"
 - dub test --arch "$ARCH"
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then meson build --default-library=static && cd build && ninja -j4 && ninja -j4 test -v && cd ..; fi # TODO: 32bit meson test
